services:
  - type: web
    name: lua-obfuscator-bot
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DISCORD_TOKEN
        sync: false
    buildCommand: |
      docker build --build-arg PYTHON_VERSION=3.11 -t obfuscator-bot .
    startCommand: docker run -e DISCORD_TOKEN=$DISCORD_TOKEN obfuscator-bot
    autoDeploy: true
